= Homepage der vLUG-Hessen

https://www.vlug-hessen.de
Für die Erstellung der Homepage benutzen wir http://jbake.org[JBake].

== JBake installieren

Am einfachsten lässt sich JBake über http://sdkman.io[sdkman] installieren.
Folge dazu folgenden Anleitungen 

* http://sdkman.io/install.html
* http://jbake.org/download.html

Für ungeduldige:

[source, bash]
----
curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk install jbake
----

NOTE: Am besten den source part direkt in die bashrc oder zshrc packen.

== Homepage backen

Um die Seite zu erstellen:

[source, bash]
----
cd www/jbake
jbake -b
----

Die übersetzte Seite befindet sich im _output_ Ordner.

Alternativ: `./build`

Um die Seite bereits vorab anzuschauen:

`jbake -s`

Startet einen jetty Server um die Seite auszuliefern.

Befindet man sich im root Verzeichnis und hat die Seite mit `./build` übersetzt muss man
`jbake -s output` benutzen.

== check links

Um die Seite auf evtl. kaputte Links zu überprüfen gibt es ein kleines helperskript
`check-links`

Dazu wird das paket `w3c-linkchecker` benötigt.


